name: Build and push Docker image

on:
  workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: 'Docker Tag'
  #       required: true
  #       default: 'latest'
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set version
      run: |
        echo "version=$(cat telethon-downloader/bottorrent.py| grep "self.VERSION =" | awk -F'=' '{print $2}' | egrep -o "[0-9.a-z-]{1,}")" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm/v7
        push: true
        tags: ghcr.io/omnia_89/telethon_downloader:latest #, omnia_89/telethon_downloader:${{ github.event.inputs.tag }}
